services:
  db:
    image: mysql:8.0
    container_name: gym_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gymmanagement
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Tự động nạp dữ liệu khi db chạy lần đầu
      - ./GymManagement_export.sql:/docker-entrypoint-initdb.d/GymManagement_export.sql

  backend:
    build:
      context: ./backend
    container_name: gym_backend
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Nối thư mục code để sửa code tự động cập nhật
      - ./backend:/var/www/html/backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: gym_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Bỏ qua node_modules trên máy thật, ưu tiên node_modules trong container
      - /app/node_modules
    environment:
      # Giúp Vite theo dõi thay đổi file mượt hơn trong container
      - CHOKIDAR_USEPOLLING=true
    # Chạy npm run dev và mở port ra ngoài bằng cờ --host
    command: npm run dev -- --host

volumes:
  db_data:
